language: python

python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  

before_install:
  pip install codecov


install: 
  "pip install -r requirements.txt"

script:
    - python setup.py install
    - py.test --doctest-glob="*.rst" --doctest-modules --ignore=setup.py 
    - coverage run tests 
  

after_success:
  - codecov
